# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches:
      - main
      - master
      - release
  pull_request:
    branches:
      - main
      - master
      - release
  workflow_dispatch:

jobs:
  build:
    name: Build with ${{ matrix.distribution }} JDK ${{ matrix.jdk }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk:
          - '23'
          - '24'
          - '25'
        distribution:
          - 'temurin'

    env:
      JAVA_PLATFORM_VERSION: ${{ matrix.jdk }}

    steps:
      # Check out sources
      - name: Fetch Sources
        uses: actions/checkout@v5.0.0
      - name: Fetch Sources of TweetwallFX-core projects
        uses: actions/checkout@v5.0.0
        with:
          path: .tweetwallFX-core/
          repository: TweetWallFX/TweetwallFX

      # Setup JDK environment for the next steps
      - name: Setup ${{ matrix.distribution }} JDK ${{ matrix.jdk }} for gradle
        uses: actions/setup-java@v5.0.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
          cache: gradle

      # Setup gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          validate-wrappers: true

      # Run assemble tasks
      - name: Run assemble tasks with toolchain JDK ${{ matrix.jdk }}
        run: ./gradlew --no-daemon --refresh-dependencies --scan --warning-mode all assemble

      # Run test tasks
      - name: Run test tasks with toolchain JDK ${{ matrix.jdk }}
        run: ./gradlew --no-daemon --scan --warning-mode all test

      # Run check tasks
      - name: Run check tasks with toolchain JDK ${{ matrix.jdk }}
        run: ./gradlew --no-daemon --scan --warning-mode all check

      # Archive test reports
      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.distribution }}-jdk${{ matrix.jdk }}-build-logs
          retention-days: 5
          path: |
            **/*.jfr
            **/hs_err_pid*.log
            **/build/reports/*
